import { CurrencySystem, ModelDefinition, Parameter, PolicyPreset } from './types';

export const defaultParameters: Parameter[] = [
  {
    id: 'laborSupply',
    name: 'Total labor supply',
    value: 100,
    unit: 'labor units',
    description: 'Total labor available to both sectors each step.',
    role: 'Sets the scale of production and employment.',
  },
  {
    id: 'sectorShareA',
    name: 'Sector A labor share',
    value: 0.55,
    unit: 'share',
    description: 'Fraction of labor going to sector A.',
    role: 'Controls how labor is split between sectors.',
  },
  {
    id: 'productivityA',
    name: 'Sector A productivity',
    value: 1.2,
    unit: 'output per labor',
    description: 'Baseline productivity for sector A.',
    role: 'Determines output per worker in sector A.',
  },
  {
    id: 'productivityB',
    name: 'Sector B productivity',
    value: 0.9,
    unit: 'output per labor',
    description: 'Baseline productivity for sector B.',
    role: 'Determines output per worker in sector B.',
  },
  {
    id: 'innovationBase',
    name: 'Base innovation rate',
    value: 0.04,
    unit: 'per step',
    description: 'Underlying rate of productivity improvements.',
    role: 'Sets the speed of frontier innovation.',
  },
  {
    id: 'diffusionBase',
    name: 'Base diffusion rate',
    value: 0.03,
    unit: 'per step',
    description: 'How quickly knowledge diffuses between sectors.',
    role: 'Controls catch-up between sectors.',
  },
  {
    id: 'ipProtection',
    name: 'IP protection strength',
    value: 0.6,
    unit: 'index',
    description: 'Strength of patent-like exclusivity and enforcement.',
    role: 'Raises private returns but can slow diffusion.',
  },
  {
    id: 'openSourceAdoption',
    name: 'Open source adoption',
    value: 0.5,
    unit: 'index',
    description: 'Share of innovations released under open licenses.',
    role: 'Boosts diffusion, can reduce private appropriability.',
  },
  {
    id: 'royaltyRate',
    name: 'Average royalty rate',
    value: 0.12,
    unit: 'share',
    description: 'Share of revenue paid for licensed IP.',
    role: 'Raises prices and rents for rights-holders.',
  },
  {
    id: 'publicFunding',
    name: 'Public R&D funding',
    value: 0.3,
    unit: 'index',
    description: 'Public investment that supports innovation broadly.',
    role: 'Offsets weak private incentives.',
  },
  {
    id: 'antitrustStrength',
    name: 'Antitrust strength',
    value: 0.4,
    unit: 'index',
    description: 'Intensity of competition policy.',
    role: 'Reduces market power and price markups.',
  },
  {
    id: 'platformOpenness',
    name: 'Platform openness',
    value: 0.5,
    unit: 'index',
    description: 'Degree of interoperability and open standards.',
    role: 'Improves diffusion and lowers entry barriers.',
  },
  {
    id: 'inequalityAversion',
    name: 'Inequality aversion',
    value: 0.6,
    unit: 'index',
    description: 'Weight society gives to distributional equity.',
    role: 'Shapes welfare metrics.',
  },
  {
    id: 'welfareWeightGrowth',
    name: 'Growth weight in welfare',
    value: 0.5,
    unit: 'index',
    description: 'Weight given to output growth in welfare metrics.',
    role: 'Balances growth vs distribution.',
  },
  {
    id: 'currencyMixCommons',
    name: 'Commons currency share',
    value: 0.2,
    unit: 'share',
    description: 'Share of transactions using commons or reciprocity currencies.',
    role: 'Adds alternative liquidity to the system.',
  },
  {
    id: 'currencyMixTime',
    name: 'Time currency share',
    value: 0.15,
    unit: 'share',
    description: 'Share of transactions using time-based currencies.',
    role: 'Adds time-based liquidity and alters welfare accounting.',
  },
];

export const currencySystems: CurrencySystem[] = [
  {
    id: 'fiat',
    name: 'Fiat currency',
    description: 'State-backed currency with standard liquidity.',
    liquidityMultiplier: 1,
    velocity: 1,
  },
  {
    id: 'commons',
    name: 'Commons/reciprocity credits',
    description: 'Relationship-based credits that favor reciprocal exchange.',
    liquidityMultiplier: 0.8,
    velocity: 1.2,
  },
  {
    id: 'time',
    name: 'Time-based currency',
    description: 'Units valued in hours of time, emphasizing care and services.',
    liquidityMultiplier: 0.6,
    velocity: 1.4,
  },
];

export const policyPresets: PolicyPreset[] = [
  {
    id: 'default',
    name: 'Balanced baseline',
    description: 'Mix of IP protection and open diffusion.',
    parameterOverrides: {},
  },
  {
    id: 'open-commons',
    name: 'Open commons acceleration',
    description: 'Strong open-source diffusion with public funding.',
    parameterOverrides: {
      openSourceAdoption: 0.85,
      publicFunding: 0.6,
      ipProtection: 0.3,
      platformOpenness: 0.8,
      royaltyRate: 0.05,
    },
  },
  {
    id: 'proprietary-max',
    name: 'Proprietary incentives',
    description: 'High exclusivity and royalties to boost private R&D.',
    parameterOverrides: {
      ipProtection: 0.9,
      royaltyRate: 0.22,
      openSourceAdoption: 0.2,
      antitrustStrength: 0.2,
    },
  },
  {
    id: 'antitrust-surge',
    name: 'Competition surge',
    description: 'Aggressive antitrust with moderate openness.',
    parameterOverrides: {
      antitrustStrength: 0.8,
      platformOpenness: 0.7,
      royaltyRate: 0.08,
      ipProtection: 0.5,
    },
  },
  {
    id: 'public-mission',
    name: 'Public mission economy',
    description: 'Public R&D drives innovation with equitable goals.',
    parameterOverrides: {
      publicFunding: 0.75,
      inequalityAversion: 0.8,
      openSourceAdoption: 0.6,
      ipProtection: 0.4,
    },
  },
  {
    id: 'platform-feudal',
    name: 'Platform feudalism',
    description: 'High market power and closed platforms.',
    parameterOverrides: {
      platformOpenness: 0.2,
      royaltyRate: 0.25,
      ipProtection: 0.8,
      antitrustStrength: 0.1,
    },
  },
  {
    id: 'multi-liquidity',
    name: 'Multi-liquidity commons',
    description: 'Complementary currencies support plural welfare.',
    parameterOverrides: {
      currencyMixCommons: 0.35,
      currencyMixTime: 0.3,
      openSourceAdoption: 0.7,
      platformOpenness: 0.7,
    },
  },
];

export const defaultModelDefinition: ModelDefinition = {
  sectors: [
    { id: 'sectorA', name: 'Manufacturing' },
    { id: 'sectorB', name: 'Services' },
  ],
  households: [
    { id: 'workers', name: 'Workers' },
    { id: 'owners', name: 'Rights holders' },
  ],
  parameters: defaultParameters,
  policyPresets,
  currencySystems,
};
